### ISSUE TITLE
Dark version?

### ISSUE THREAD

**Issue by zoomlogo** [agarick/semant#2]

**Comment by blobject** [comment]
ohai!

If you mean light text on a dark background, you could just flip the colors, so that "foreground" becomes background, "background" becomes foreground, "Blue" becomes normal blue, "blue" becomes bright blue, etc. (I'm using the names as seen in the readme.) To do the actual flipping, you'll have to configure your program manually because this project doesn't provide any preset things, just the color definitions.

One of the screenshots in the readme shows the reversed color sets, side by side.

If you mean a darker shade of the theme (but still dark text on a light background), then that doesn't exist (yet). It wouldn't be too hard to come up with darker variations yourself though. If you are so inclined, you could take the values written in the table in the readme, plug them into a color calculator (like https://www.nixsensor.com/free-color-converter/) and play around with the "L" value to make a color lighter or darker.

**edit:** My mistake. Actually this project does provide a few preset configurations, but only for the dark-on-light color set for a few editors. I guess I could provide dark configuration files for them. I don't really plan on supplying configurations for other editors or applications though.

**Comment by zoomlogo** [comment]
> If you mean light text on a dark background, you could just flip the colors, so that "foreground" becomes background, "background" becomes foreground, "Blue" becomes normal blue, "blue" becomes bright blue, etc. (I'm using the names as seen in the readme.) To do the actual flipping, you'll have to configure your program manually because this project doesn't provide any preset things, just the color definitions.


I meant that, thank you very much.
